---
title: "SIR model simulation"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo    = TRUE,
  message = FALSE,
  warning = FALSE,
  error   = FALSE
)
```

## Load packages
```{r}
library(deSolve)
library(tidyverse)
```

## Set initial values
```{r}
I_init <- 20/8*1e-6
S_init <- 1 - I_init
R_init <- 0

init <- c(S = S_init, I = I_init, R = R_init)
```

## Set parameters
```{r}
R0   <- 2.2
pi_r <- 1 / 8
pi_s <- R0 * pi_r

parameters <- c(pi_s = pi_s, pi_r = pi_r)
```

## Set time frame
```{r}
times <- seq(0, 200, by = 1)
```

## Formulate the SIR model
```{r}
sir <- function(time, state, parameters) {

  with(as.list(c(state, parameters)), {

    dS <- -pi_s * S * I
    dI <-  pi_s * S * I - pi_r * I
    dR <-  pi_r * I

    return(list(c(dS, dI, dR)))
  })
}
```


## Solve ODE
```{r}
out <- ode(
  y = init,
  times = times,
  func = sir,
  parms = parameters
)
```

## Plot pandemic progress
```{r}
out_long <- out %>% 
  as.data.frame() %>% 
  pivot_longer(-time, names_to = "group", values_to = "prop")

out_long %>% 
  ggplot(aes(x = time, y = prop * 100, color = group)) +
  geom_line(size = 1) + 
  theme_light() + 
  labs(
    x = "days",
    y = "% of population"
  )
```

